#Fri Jan 26 12:51:22 UTC 2024
micronaut:
  application:
    name: SharedObjectsService
  security:
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: '"${JWT_GENERATOR_SIGNATURE_SECRET:pleaseChangeThisSecretForANewOne}"'
mongodb:
  uri: mongodb://localhost:27017/Placard?uuidRepresentation=standard